### ISSUE TITLE
Undefined symbols for VisionPro

### ISSUE THREAD

**Issue by magnustviberg** [shogo4405/HaishinKit.swift#1507]
### Describe the bug

I have created an empty project and imported the framework using SPM (https://github.com/shogo4405/HaishinKit.swift). The package dependencies are HaishinKit 1.9.1 and Logboard 2.5.0. When I remove all supported Desitnations except Apple Vision (visionOS) the project won't compile. The error I get is (I have removed a lot of the error output because it was really really long): 

`ld: warning: Could not find or use auto-linked framework 'AudioUnit': framework 'AudioUnit' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
Undefined symbols for architecture arm64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::find(char, unsigned long) const", referenced from:
      ...
  "___gxx_personality_v0", referenced from:
      /Users/name/Library/Developer/Xcode/DerivedData/projectName-gswbezpkknxtzfeivkrkhcstfvjs/Build/Products/Debug-xros/libsrt.a[24](srt_c_api.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### To Reproduce

- Create a new project.
- Import dependencies using SPM https://github.com/shogo4405/HaishinKit.swift.
- Set Apple Vision (visionOS) as Supported Destination
- Build project (Fails)

### Expected behavior

- Create a new project.
- Import dependencies using SPM https://github.com/shogo4405/HaishinKit.swift.
- Set Apple Vision (visionOS) as Supported Destination
- Build project

### Version

1.9.1

### Smartphone info.

Apple Vision Pro - visionOS 1.2

**Comment by shogo4405** [comment]
Is it a Vision Pro physical device or a simulator? I don’t have a Vision Pro physical device, so I haven’t been able to verify it.
Is it correct that you want to use the SRT protocol?

**Comment by magnustviberg** [comment]
> Is it a Vision Pro physical device or a simulator? I don’t have a Vision Pro physical device, so I haven’t been able to verify it. Is it correct that you want to use the SRT protocol?

Both. Doesn't work in the 1.2 simulator either

**Comment by shogo4405** [comment]
1. I was able to reproduce it locally. Thank you for the report.
1. It worked with the example. I suspect it might be something related to SPM.

I'm a bit unfamiliar with this issue, so it might take some time to resolve. If there are other experts available, I'd appreciate it if you could inform them.

**Comment by shogo4405** [comment]
1. Xcode 16.1
2. By adding `libc++.1.tbd` to Link Binary With Libraries, I was able to build successfully.

<img width="1368" alt="スクリーンショット 2024-12-15 23 23 11" src="https://github.com/user-attachments/assets/7bf63b56-dcd2-4801-826e-3b2877ae1e9d" />
